//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerformanceLabsFramework.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PerformanceLabsFramework.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * Bootstrap v2.0.4
        /// *
        /// * Copyright 2012 Twitter, Inc
        /// * Licensed under the Apache License v2.0
        /// * http://www.apache.org/licenses/LICENSE-2.0
        /// *
        /// * Designed and built with all the love in the world @twitter by @mdo and @fat.
        /// */
        ///
        ///article,
        ///aside,
        ///details,
        ///figcaption,
        ///figure,
        ///footer,
        ///header,
        ///hgroup,
        ///nav,
        ///section {
        ///  display: block;
        ///}
        ///
        ///audio,
        ///canvas,
        ///video {
        ///  display: inline-block;
        ///  *display: inline;
        ///  *zoom: 1;
        ///}
        ///
        ///audio:not([controls]) {
        ///  display: none;
        ///}
        ///
        ///html {
        ///  font-size: 100%;
        ///  -webkit-text-size- [rest of string was truncated]&quot;;.
        /// </summary>
        public static string bootstrap {
            get {
                return ResourceManager.GetString("bootstrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* =========================================================
        /// * bootstrap-modal.js v2.0.4
        /// * http://twitter.github.com/bootstrap/javascript.html#modals
        /// * =========================================================
        /// * Copyright 2012 Twitter, Inc.
        /// *
        /// * Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
        /// * you may not use this file except in compliance with the License.
        /// * You may obtain a copy of the License at
        /// *
        /// * http://www.apache.org/licenses/LICENSE-2.0
        /// *
        /// * Unless required by applicable l [rest of string was truncated]&quot;;.
        /// </summary>
        public static string bootstrap_modal {
            get {
                return ResourceManager.GetString("bootstrap_modal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * Bootstrap Responsive v2.0.4
        /// *
        /// * Copyright 2012 Twitter, Inc
        /// * Licensed under the Apache License v2.0
        /// * http://www.apache.org/licenses/LICENSE-2.0
        /// *
        /// * Designed and built with all the love in the world @twitter by @mdo and @fat.
        /// */
        ///
        ///.clearfix {
        ///  *zoom: 1;
        ///}
        ///
        ///.clearfix:before,
        ///.clearfix:after {
        ///  display: table;
        ///  content: &quot;&quot;;
        ///}
        ///
        ///.clearfix:after {
        ///  clear: both;
        ///}
        ///
        ///.hide-text {
        ///  font: 0/0 a;
        ///  color: transparent;
        ///  text-shadow: none;
        ///  background-color: transparent;
        ///  border: 0;
        ///}
        ///
        ///.input-block [rest of string was truncated]&quot;;.
        /// </summary>
        public static string bootstrap_responsive {
            get {
                return ResourceManager.GetString("bootstrap_responsive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! jQuery v1.7.1 jquery.com | jquery.org/license */
        ///(function( window, undefined ) {
        ///
        ///// Use the correct document accordingly with window argument (sandbox)
        ///var document = window.document,
        ///	navigator = window.navigator,
        ///	location = window.location;
        ///var jQuery = (function() {
        ///
        ///// Define a local copy of jQuery
        ///var jQuery = function( selector, context ) {
        ///		// The jQuery object is actually just the init constructor &apos;enhanced&apos;
        ///		return new jQuery.fn.init( selector, context, rootjQuery );
        ///	},
        ///
        ///	// Map over jQue [rest of string was truncated]&quot;;.
        /// </summary>
        public static string jquery {
            get {
                return ResourceManager.GetString("jquery", resourceCulture);
            }
        }
        
        public static byte[] MiniProfiler {
            get {
                object obj = ResourceManager.GetObject("MiniProfiler", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
